/**
 * gate command — single-command validation gate.
 *
 * Presets:
 *   nemyo       — Nemyo ecosystem (web, extension, API, Flutter)
 *   neoxtemus   — Neoxtemus AI desktop (boot, nav, assistant, cargo tests, artifact policy)
 *
 * Runs all automation configs + native tests in sequence.
 * Produces a consolidated markdown report and exits non-zero if anything fails.
 */
import { resolve } from 'path';
import { execSync } from 'child_process';
import { writeFileSync, mkdirSync, existsSync, readdirSync, statSync } from 'fs';
import { join } from 'path';
import { run } from '../../core/orchestrator.js';
import { loadGateSuite } from '../../operator/suites/load.js';
import type { GateStep } from '../../operator/suites/types.js';

export interface GateStepResult {
  name: string;
  verdict: 'PASS' | 'FAIL';
  runId: string | null;
  durationMs: number;
  flowCount: number;
  artifactDir: string | null;
  error: string | null;
}

export interface GateExecutionResult {
  preset: string;
  label: string;
  overallVerdict: 'PASS' | 'FAIL';
  results: GateStepResult[];
  reportPath: string;
  verdictPath: string;
  totalMs: number;
}

/**
 * Artifact policy: reject release binaries/installers in the repo
 * unless NEOXTEN_BUILD_NOW=1 is set.
 */
function runArtifactPolicy(root: string): { passed: boolean; violations: string[] } {
  if (process.env.NEOXTEN_BUILD_NOW === '1') {
    return { passed: true, violations: [] };
  }

  const DISALLOWED_EXTENSIONS = ['.msi', '.nsis', '.appimage', '.dmg'];
  const DISALLOWED_PATTERNS = ['-setup.exe', '-installer.exe'];
  const EXCLUDE_DIRS = new Set(['node_modules', '.git', 'target', 'bin', 'dist', '.neoxten-out']);

  const violations: string[] = [];

  function walk(dir: string, rel: string) {
    let entries: string[];
    try {
      entries = readdirSync(dir);
    } catch {
      return;
    }
    for (const entry of entries) {
      if (EXCLUDE_DIRS.has(entry)) continue;
      const full = join(dir, entry);
      const relPath = rel ? `${rel}/${entry}` : entry;
      let stat;
      try {
        stat = statSync(full);
      } catch {
        continue;
      }
      if (stat.isDirectory()) {
        walk(full, relPath);
      } else {
        const lower = entry.toLowerCase();
        const isDisallowed =
          DISALLOWED_EXTENSIONS.some((ext) => lower.endsWith(ext)) ||
          DISALLOWED_PATTERNS.some((pat) => lower.includes(pat));
        if (isDisallowed) {
          violations.push(relPath);
        }
      }
    }
  }

  walk(root, '');
  return { passed: violations.length === 0, violations };
}

function generateReport(
  presetLabel: string,
  results: GateStepResult[],
  overallVerdict: 'PASS' | 'FAIL',
  totalMs: number,
): string {
  const now = new Date().toISOString();
  const passed = results.filter((r) => r.verdict === 'PASS').length;
  const failed = results.filter((r) => r.verdict === 'FAIL').length;

  let md = `# ${presetLabel} Report\n\n`;
  md += `**Verdict:** ${overallVerdict === 'PASS' ? 'PASS' : 'FAIL'}\n`;
  md += `**Timestamp:** ${now}\n`;
  md += `**Duration:** ${(totalMs / 1000).toFixed(1)}s\n`;
  md += `**Steps:** ${passed} passed, ${failed} failed, ${results.length} total\n\n`;
  md += `---\n\n`;
  md += `| # | Component | Verdict | Run ID | Duration | Flows | Artifacts |\n`;
  md += `|---|-----------|---------|--------|----------|-------|-----------|\n`;

  results.forEach((r, i) => {
    const verdict = r.verdict === 'PASS' ? 'PASS' : 'FAIL';
    const runId = r.runId ?? '—';
    const dur = `${(r.durationMs / 1000).toFixed(1)}s`;
    const flows = r.flowCount > 0 ? String(r.flowCount) : '—';
    const artifacts = r.artifactDir ?? '—';
    md += `| ${i + 1} | ${r.name} | ${verdict} | ${runId} | ${dur} | ${flows} | ${artifacts} |\n`;
  });

  if (failed > 0) {
    md += `\n---\n\n## Failures\n\n`;
    results
      .filter((r) => r.verdict === 'FAIL')
      .forEach((r) => {
        md += `### ${r.name}\n\n`;
        md += `\`\`\`\n${r.error ?? 'Unknown error'}\n\`\`\`\n\n`;
      });
  }

  md += `\n---\n\n`;
  md += `*Generated by NeoXten Automation Framework — ${presetLabel}*\n`;

  return md;
}

/** Run a gate suite (declarative `suites/<preset>.yaml`) without `process.exit` — for API / runner. */
export async function executeGateSuite(opts: {
  preset: string;
  frameworkRoot?: string;
  outDir?: string;
  skipIntegration?: boolean;
}): Promise<GateExecutionResult> {
  const preset = opts.preset;
  const frameworkRoot = opts.frameworkRoot ?? process.cwd();
  const suite = loadGateSuite(frameworkRoot, preset);
  const { steps, displayName: label } = suite;
  const outDir = resolve(frameworkRoot, opts.outDir ?? '.neoxten-out');
  const results: GateStepResult[] = [];
  const gateStart = Date.now();

  for (const step of steps) {
    const stepStart = Date.now();

    const skipIntegration =
      opts.skipIntegration ||
      process.env.NEMYO_SKIP_INTEGRATION === '1' ||
      process.env.NEMYO_SKIP_INTEGRATION === 'true';
    if (step.type === 'flutter_integration' && skipIntegration) {
      results.push({
        name: step.name,
        verdict: 'PASS',
        runId: null,
        durationMs: 0,
        flowCount: 0,
        artifactDir: null,
        error: null,
      });
      continue;
    }

    if (step.type === 'yaml' && step.config) {
      try {
        const configPath = resolve(frameworkRoot, step.config);
        const stepOutDir = resolve(outDir, step.outSubDir ?? step.name);
        const { verdict, artifacts } = await run({ configPath, outDir: stepOutDir });

        const flowCount = verdict.logExcerpts
          ? verdict.logExcerpts.filter((l: string) => l.startsWith('Executing flow:')).length
          : 0;

        results.push({
          name: step.name,
          verdict: verdict.verdict as 'PASS' | 'FAIL',
          runId: verdict.runId,
          durationMs: Date.now() - stepStart,
          flowCount,
          artifactDir: artifacts.runDir,
          error: verdict.verdict === 'FAIL'
            ? verdict.logExcerpts?.slice(-1)[0] ?? 'Flow failed'
            : null,
        });

      } catch (e) {
        const err = e instanceof Error ? e.message : String(e);
        results.push({
          name: step.name,
          verdict: 'FAIL',
          runId: null,
          durationMs: Date.now() - stepStart,
          flowCount: 0,
          artifactDir: null,
          error: err,
        });
      }
    } else if (step.type === 'flutter') {
      try {
        const cwd = resolve(frameworkRoot, step.cwd ?? '.');
        const testPath = step.testPath ?? 'test/';
        const cmd = `flutter test ${testPath} --no-pub`;
        const output = execSync(cmd, {
          cwd,
          encoding: 'utf-8',
          timeout: 180000,
          stdio: ['ignore', 'pipe', 'pipe'],
        });

        const testCount = (output.match(/\+(\d+)/g) ?? []).length;

        results.push({
          name: step.name,
          verdict: 'PASS',
          runId: null,
          durationMs: Date.now() - stepStart,
          flowCount: testCount,
          artifactDir: null,
          error: null,
        });
      } catch (e) {
        const err = e instanceof Error ? (e as { stderr?: string }).stderr ?? e.message : String(e);
        results.push({
          name: step.name,
          verdict: 'FAIL',
          runId: null,
          durationMs: Date.now() - stepStart,
          flowCount: 0,
          artifactDir: null,
          error: typeof err === 'string' ? err.slice(0, 500) : String(err),
        });
      }
    } else if (step.type === 'flutter_integration') {
      try {
        const cwd = resolve(frameworkRoot, step.cwd ?? '.');
        const target = step.testTarget ?? 'integration_test/app_test.dart';
        const deviceId = step.deviceId ?? process.env.NEMYO_FLUTTER_DEVICE_ID ?? '';
        const deviceArg = deviceId ? ` -d ${deviceId}` : '';
        const cmd = `flutter test ${target}${deviceArg}`;
        const output = execSync(cmd, {
          cwd,
          encoding: 'utf-8',
          timeout: 300000,
          stdio: ['ignore', 'pipe', 'pipe'],
        });

        const testCount = (output.match(/\+(\d+)/g) ?? []).length;

        results.push({
          name: step.name,
          verdict: 'PASS',
          runId: null,
          durationMs: Date.now() - stepStart,
          flowCount: testCount,
          artifactDir: null,
          error: null,
        });
      } catch (e) {
        const err = e instanceof Error ? (e as { stderr?: string }).stderr ?? e.message : String(e);
        results.push({
          name: step.name,
          verdict: 'FAIL',
          runId: null,
          durationMs: Date.now() - stepStart,
          flowCount: 0,
          artifactDir: null,
          error: typeof err === 'string' ? err.slice(0, 500) : String(err),
        });
      }
    } else if (step.type === 'cargo') {
      try {
        if (process.platform === 'win32') {
          try {
            execSync('taskkill /F /IM neoxtemus.exe', { stdio: 'ignore', timeout: 5000 });
          } catch {}
          try {
            execSync('taskkill /F /IM neoxtemus-app.exe', { stdio: 'ignore', timeout: 5000 });
          } catch {}
          try {
            execSync('taskkill /F /IM cargo-tauri.exe', { stdio: 'ignore', timeout: 5000 });
          } catch {}
        }
        const cwd = resolve(frameworkRoot, step.cwd ?? '.');
        const output = execSync('cargo test --workspace', {
          cwd,
          encoding: 'utf-8',
          timeout: 300000,
          stdio: ['ignore', 'pipe', 'pipe'],
        });

        const passMatches = output.match(/test result: ok\./g) ?? [];

        results.push({
          name: step.name,
          verdict: 'PASS',
          runId: null,
          durationMs: Date.now() - stepStart,
          flowCount: passMatches.length,
          artifactDir: null,
          error: null,
        });
      } catch (e) {
        const err = e instanceof Error ? (e as { stdout?: string }).stdout ?? e.message : String(e);
        results.push({
          name: step.name,
          verdict: 'FAIL',
          runId: null,
          durationMs: Date.now() - stepStart,
          flowCount: 0,
          artifactDir: null,
          error: typeof err === 'string' ? err.slice(0, 1000) : String(err),
        });
      }
    } else if (step.type === 'policy') {
      const policyRoot = resolve(frameworkRoot, step.policyRoot ?? '.');
      const result = runArtifactPolicy(policyRoot);

      results.push({
        name: step.name,
        verdict: result.passed ? 'PASS' : 'FAIL',
        runId: null,
        durationMs: Date.now() - stepStart,
        flowCount: 0,
        artifactDir: null,
        error: result.passed
          ? null
          : `Disallowed release artifacts found:\n${result.violations.map((v) => `  - ${v}`).join('\n')}\nSet NEOXTEN_BUILD_NOW=1 to override.`,
      });
    }
  }

  const totalMs = Date.now() - gateStart;
  const overallVerdict = results.every((r) => r.verdict === 'PASS') ? 'PASS' : 'FAIL';

  const reportDir = resolve(outDir, 'gate');
  if (!existsSync(reportDir)) mkdirSync(reportDir, { recursive: true });

  const reportSlug = preset.toLowerCase();
  const reportPath = resolve(reportDir, `${reportSlug}-gate-report.md`);
  const report = generateReport(label, results, overallVerdict, totalMs);
  writeFileSync(reportPath, report, 'utf-8');

  const verdictPath = resolve(reportDir, 'gate-verdict.json');
  writeFileSync(
    verdictPath,
    JSON.stringify(
      {
        preset,
        verdict: overallVerdict,
        timestamp: new Date().toISOString(),
        durationMs: totalMs,
        steps: results.map((r) => ({
          name: r.name,
          verdict: r.verdict,
          runId: r.runId,
          durationMs: r.durationMs,
        })),
      },
      null,
      2,
    ),
    'utf-8',
  );

  return {
    preset,
    label,
    overallVerdict,
    results,
    reportPath,
    verdictPath,
    totalMs,
  };
}

export async function gateCommand(opts: {
  preset?: string;
  outDir?: string;
  skipIntegration?: boolean;
}): Promise<void> {
  const preset = opts.preset ?? 'nemyo';
  const frameworkRoot = process.cwd();
  let result: GateExecutionResult;
  try {
    result = await executeGateSuite({
      preset,
      frameworkRoot,
      outDir: opts.outDir,
      skipIntegration: opts.skipIntegration,
    });
  } catch (e) {
    const msg = e instanceof Error ? e.message : String(e);
    console.error(`Unknown or invalid suite "${preset}": ${msg}`);
    console.error('Built-in suites: see suites/*.yaml (e.g. nemyo, neoxtemus, operator)');
    process.exit(2);
  }

  console.log(`\n  -- ${result.label}: ${result.overallVerdict} --`);
  console.log(`  Report: ${result.reportPath}`);
  console.log(`  Verdict: ${result.verdictPath}`);
  console.log(`  Duration: ${(result.totalMs / 1000).toFixed(1)}s\n`);

  process.exit(result.overallVerdict === 'PASS' ? 0 : 1);
}
